    sudo docker build -t openach/openach 
    docker-compose up -d

       docker-compose run --rm cli
   docker-compose run --rm cli user create --user_login=ericat53 --user_password=Txdl0623 --user_email_address=ericat53@yahoo.com --user_first_name=Erica --user_last_name=Trahan
   docker-compose run --rm cli user setup --user_id=<user-id-from-previous-step> --name="Test Originator" --identification=15870238 --routing_number=086300012 --account_number=116761942
   # Note the IDs generated by these commands as you will need them later.
   
